Ser/deserialize events
i1i1/rpc-go pull request #3
Opened 2021-03-09 15:26 UTC by i1i1

Signed-off-by: i1i1 <vanyarybin1@live.ru>

2021-03-10 08:30 UTC, Mexator requested changes

2021-03-10 08:30 UTC, Mexator commented on pkg/game/game.go
> +	}
Нахуя?

2021-03-10 08:30 UTC, Mexator commented on pkg/game/game.go
> +	}
У тебя ж уже такая же структура определена в events

2021-03-10 08:30 UTC, Mexator commented on pkg/game/game.go
> +		Self:     events.Player{ID: selfID, Nick: nickname},
cr -> gr
А лучше не называй двумя символами вообще ничего

2021-03-10 08:30 UTC, Mexator commented on pkg/game/game.go
> +	return out
Map?!

2021-03-10 08:30 UTC, Mexator commented on pkg/game/game.go
> +		err = dec.Decode(&event)
А ты не забыл зарегать в gob Event?

2021-03-10 08:30 UTC, Mexator commented on pkg/ui/ui.go
> +// The Run method will draw the UI to the terminal in "fullsgreen"
fulls_G_reen LOOOOL

2021-03-10 08:30 UTC, Mexator commented on pkg/ui/ui.go
> +		ui.displaySelfEvent(event)
Наверное, если publish error, стоит self event отрисовать красным цветом, например

2021-03-10 09:10 UTC, i1i1 commented on pkg/game/game.go
> +	}
Для серилизации. Возможно лучше назвать SerDeEvent или как то дать контекст серилизации

2021-03-10 09:10 UTC, i1i1 commented on pkg/game/game.go
> +	return out
Это хешсет. Такая неочевидная идиома в го

2021-03-10 09:11 UTC, i1i1 commented on pkg/game/game.go
> +		err = dec.Decode(&event)
`init()`

2021-03-10 09:11 UTC, i1i1 commented on pkg/ui/ui.go
> +// The Run method will draw the UI to the terminal in "fullsgreen"
sed 's/cr/gr/g'

Там просто изначально был этот акроним.

2021-03-10 09:12 UTC, i1i1 commented on pkg/ui/ui.go
> +		ui.displaySelfEvent(event)
Вот можешь это поправить в следующем комите!

2021-03-10 09:12 UTC, i1i1 commented on pkg/game/game.go
> +		Self:     events.Player{ID: selfID, Nick: nickname},
Окей

2021-03-10 09:21 UTC, i1i1 commented on pkg/game/game.go
> +		err = dec.Decode(&event)
Имплементации интерфейсов нужно только регистрировать.

2021-03-10 09:37 UTC, i1i1 commented on pkg/game/game.go
> +	return out
Во многих языках подобная штука. `struct{}{}` -- структура с нулевым размером, поэтому:
```
type HashSet<K> = HashMap<K, ()>
```

2021-03-10 09:38 UTC, i1i1 commented on pkg/game/game.go
> +		err = dec.Decode(&event)
Если что можно запустить эту штуку и позапускать команды. Иначе бы серилизация десерилизация бы фейлилась во время рантайма.

2021-03-10 09:38 UTC, i1i1 commented on pkg/ui/ui.go
> +		ui.displaySelfEvent(event)
good-first-issue

2021-03-12 14:42 UTC, Mexator approved these changes

2021-03-12 14:49 UTC, merged